=head1 Things to do

=head2 Game mechanics

=over 4

=item *

Implement a universal time ticker that governs production
etc. across the universe for the playtime. All actions
would be tied to a point in time.

=item *

Is travel through wormholes instantaneous?

=item *

Implement a renderer for the graph of the known universe

=item *

Implement resource transformation journal that trails how/when/where entities
enter and leave the system. This is easy for trade
but how are consumables handled? Should fuel consumption
issue one log entry per (instantaneous) trip or should it
issue multiple entries as the journey progresses? The same
issue arises with factories that consume raw materials
to produce refined materials.

Potentially, just with The Account System, the amount of
raw and refined materials at a point in time is just the
sum of the journals for the place, at least up to the last
consolidation point. This would leave the burden of accounting
for the transformation with the transformator. If you start a
transformation and then interrupt or finish it, at that point
in time, the calculation needs to be updated with a new log
entry. This approach makes it harder to inspect the "current situation".
Maybe every such inspection causes a commit of the situation?

=back

=head2 Missions

=over 4

=item *

Implement mission attributes as invisible, untradeable widgets
that attach to the player (instead of the ship?)

=item *

Implement FedEx missions

=back

=head2 Economy

=over 4

=item *

Do commodities have a "kind" (like "food"/"weapon"/"slave") and
a specifc type?

=item *

Implement a "standard" set of commodities in L<Demiurge>

=item *

Implement trading posts with fixed prices

=item *

Implement specialized trading posts that only trade
in specific product categories

=item *

Implement equipment trading posts that trade ships, weapons
and other things to outfit the ship with

=item *

Implement trading posts with variable prices depending
on the last delivery

=item *

Implement NCP traders that shuffle items around

=back

=head2 Environment

=over 4

=item *

Implement "News" generator

=back

=head2 Artwork

Will we use a web frontend? Or Firefox as a frontend?

=over 4

=item *

Ship configuration artwork for the ship parts

=item *

Create commodity artwork

=back

=head1 Things already done